In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
df = pd.read_parquet("../data/cleaned_data.parquet")
df.head(3)

,order_id,order_date,order_hour,day_of_week,is_weekend,is_festival,weather,pickup_zone,dropoff_zone,vehicle_type,...,road_distance_km,delivery_distance_category,traffic_level,number_of_signals,average_speed_kmph,delivery_priority,time_taken_min,month,traffic_lvl_code,rider_experience_group
0,ORD000001,2025-10-28,8,tuesday,0,0,clear,cbd,commercial,scooter,...,30.55,long,moderate,15,28.7,normal,91,October,2,3–5 years
1,ORD000002,2025-09-26,12,friday,0,0,rain,cbd,cbd,scooter,...,2.25,short,moderate,17,23.3,normal,21,September,2,0–2 years
2,ORD000003,2025-01-26,18,sunday,1,0,clear,residential,residential,scooter,...,10.15,long,moderate,8,28.9,normal,52,January,2,3–5 years

In [7]:
df["rider_experience_group"].unique()

['3–5 years', '0–2 years', '12+ years', '9–11 years', '6–8 years']
Categories (5, str): ['0–2 years' < '3–5 years' < '6–8 years' < '9–11 years' < '12+ years']

In [15]:
# Does more experience make riders faster? expeerience group to delivery time
exp_to_del_time = df.groupby("rider_experience_group").agg(
    avg_delivery_time=pd.NamedAgg(column="time_taken_min", aggfunc="mean")
).round(2).reset_index()
exp_to_del_time

  rider_experience_group  avg_delivery_time
0              0–2 years              86.60
1              3–5 years              84.12
2              6–8 years              82.54
3             9–11 years              80.98
4              12+ years              78.98

In [19]:
# Does rider rating predict delivery speed? 
rating_del_speed = df["rider_rating"].corr(df["time_taken_min"])
print(f"Correlation between rider rating and delivery speed: {rating_del_speed:.2f}")

Correlation between rider rating and delivery speed: -0.04